// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemeHotel;

#nullable disable

namespace SystemeHotel.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251226164317_SeedReservations")]
    partial class SeedReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SystemeHotel.Models.Chambre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<double>("Prix")
                        .HasColumnType("double");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Chambres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = "101",
                            Prix = 50.0,
                            Statut = 0,
                            Type = "Simple"
                        },
                        new
                        {
                            Id = 2,
                            Numero = "102",
                            Prix = 80.0,
                            Statut = 0,
                            Type = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Numero = "201",
                            Prix = 150.0,
                            Statut = 0,
                            Type = "Suite"
                        });
                });

            modelBuilder.Entity("SystemeHotel.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "dupont@example.com",
                            Nom = "Dupont",
                            Telephone = "0123456789"
                        },
                        new
                        {
                            Id = 2,
                            Email = "martin@example.com",
                            Nom = "Martin",
                            Telephone = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "durand@example.com",
                            Nom = "Durand",
                            Telephone = "0567891234"
                        });
                });

            modelBuilder.Entity("SystemeHotel.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("SystemeHotel.Models.Paiement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FactureId")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<double>("Montant")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("FactureId")
                        .IsUnique();

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("SystemeHotel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChambreId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChambreId");

                    b.HasIndex("ClientId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChambreId = 1,
                            ClientId = 1,
                            DateDebut = new DateTime(2025, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Statut = 1
                        },
                        new
                        {
                            Id = 2,
                            ChambreId = 2,
                            ClientId = 2,
                            DateDebut = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Statut = 0
                        });
                });

            modelBuilder.Entity("SystemeHotel.Models.Facture", b =>
                {
                    b.HasOne("SystemeHotel.Models.Reservation", "Reservation")
                        .WithOne("Facture")
                        .HasForeignKey("SystemeHotel.Models.Facture", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("SystemeHotel.Models.Paiement", b =>
                {
                    b.HasOne("SystemeHotel.Models.Facture", "Facture")
                        .WithOne("Paiement")
                        .HasForeignKey("SystemeHotel.Models.Paiement", "FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facture");
                });

            modelBuilder.Entity("SystemeHotel.Models.Reservation", b =>
                {
                    b.HasOne("SystemeHotel.Models.Chambre", "Chambre")
                        .WithMany("Reservations")
                        .HasForeignKey("ChambreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemeHotel.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambre");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("SystemeHotel.Models.Chambre", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SystemeHotel.Models.Facture", b =>
                {
                    b.Navigation("Paiement");
                });

            modelBuilder.Entity("SystemeHotel.Models.Reservation", b =>
                {
                    b.Navigation("Facture");
                });
#pragma warning restore 612, 618
        }
    }
}
